### PR TITLE
Allow ember-resources v6

### PR DESCRIPTION
**Pull request by anehx**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
thank you!!

**Comment by anehx** [comment]
@NullVoxPopuli bd70ac2d0755968609b3105fca333bfc49b9b0b3 should fix the failing pipeline

**Comment by NullVoxPopuli** [comment]
Looks like I have some bitrot to figure out :sweat_smile:

**Comment by NullVoxPopuli** [comment]
This is now in ember-data-resources@v5 

https://github.com/NullVoxPopuli/ember-data-resources/pull/296

**Pull request closed without merging**
